### ISSUE TITLE
Adding city names for the internships. 

### ISSUE THREAD

**Issue by islamborghini** [nicolasgarza/early-cs-internships#2]
Instead of 'Multiple Locations', specify locations

**Comment by nicolasgarza** [comment]
Yea i'll get on that in a couple days, sorry 😅 I'll just assume they have the same locations as the main internships (like the ones open to all ppl), and adjust accordingly when the internships actually release

**Comment by nicolasgarza** [comment]
Ok - I'll update the field as the internships are posted, I don't really have a method of getting all the locations beforehand. Thankfully I can just copy them from the simplify repo too, so i can give the nice dropdowns like with salesforce (but i prob wont bother with Deloitte, they have like 30 locations lol).

**Comment by islamborghini** [comment]
Sounds great! Closing the issue
